# -*- coding: utf-8 -*-
"""Tarea1VD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19H3EgpoZJelLuQjceoMPcd5zE4NfB4zc

## Ignacio Muñoz Ulloa 202173096-6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("drive/MyDrive/DataColab/prevalence-of-undernourishment.csv")
value_col = df.columns[-1]

regions = ['Northern Africa (FAO)','Western Africa (FAO)','Middle Africa (FAO)' ,'Eastern Africa (FAO)', 'Southern Africa (FAO)',
           'Western Asia (FAO)',  'Central Asia (FAO)', 'South-eastern Asia (FAO)', 'Southern Asia (FAO)','Eastern Asia (FAO)' , 'South America (FAO)', 'Caribbean (FAO)',
           'Northern America and Europe (FAO)']

plot_df = (
    df[df["Entity"].isin(regions)]
    .pivot(index="Year", columns="Entity", values=value_col)
    .sort_index()
)
plot_df = plot_df[regions]

years = plot_df.index.to_numpy()
values = plot_df.to_numpy()

theta_edges = np.linspace(0, 2 * np.pi, len(regions) + 1)


r_edges = np.arange(len(years) + 1)

Theta, R = np.meshgrid(theta_edges, r_edges)

fig = plt.figure(figsize=(11, 11))
ax = plt.subplot(111, projection="polar")
mesh = ax.pcolormesh(Theta, R, values, shading="flat")

ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)

theta_centers = (theta_edges[:-1] + theta_edges[1:]) / 2
ax.tick_params(axis='x', pad=18)
ax.set_xticks(theta_centers)
ax.set_xticklabels(
    [
        "África del norte",
        "África occidental",
        "África central",
        "África oriental",
        "África austral",
        "Asia occidental",
        "Asia central",
        "Sudeste asiático",
        "Asia meridional",
        "Asia oriental",
        "Sudamérica",
        "Caribe",
        "América del norte y Europa",
    ],
    fontsize=10,
)

tick_positions = [ 4.5,  8.5,  12.5,  16.5,  20.5, + 24.5]
tick_labels = ["2004", "2008", "2012", "2016", "2020", "2024"]

ax.set_yticks(tick_positions)
ax.set_yticklabels(tick_labels, fontsize=9, color="white")
ax.set_rlabel_position(190)
"""
for label in ax.get_yticklabels():
    label.set_bbox(dict(facecolor="black", alpha=0.15, edgecolor="none", pad=1.5))
"""
ax.set_title(
    "Prevalencia de desnutricion por región (2000-2024)\n",
    #"Mapa de calor radial",
    va="bottom",
    fontsize=15,
    pad=28,
)
"""
ax.text(
    0,
    0,
    "Anillos = años\nSectores = regiones",
    ha="center",
    va="center",
    fontsize=10,
)
"""
cbar = plt.colorbar(mesh, pad=0.10, shrink=0.82)
cbar.set_label("Porcentaje de población desnutrida")

fig.text(
    0.5,
    0.03,
    "Fuente: FAO (2025), procesado por Our World in Data. "
    "Cada anillo representa un año y cada sector una región seleccionada.",
    ha="center",
    fontsize=10,
)

plt.tight_layout()
plt.show()